---
title: "Guide to MCGD"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GuideToOptizyme}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

**MCGD** stands for **Monte Carlo Gradient Descent** and is the optimization algorithm that is the heart of Optizyme's functionality. MCGD can be used to optimize enzyme ratios for a cell-free biological system.

First we will provide an explanation of how a gradient descent algorithm works. 

##

The simplest way to explain this algorithm is with an **analogy**. Imagine walking over a a very foggy landscape, so foggy that you cannot see past where you are standing. This landscape has a lot of hills and dips, and you are trying to find the lowest point of the landscape. The only tool available to you is a compass, but instead of telling you which way is north, this compass points in the direction of greatest decrease in altitude. So if you were standing on the side of a hill, the compass would point straight down the hill.  To move around, you look at the compass, and then you take a step in the direction it is pointing. You then look again, and take a step in the new direction it is pointing. At some point, you should reach the lowest point on the landscape. Our gradient descent algorithm uses this idea to find the most efficient ratio of enzymes. The foggy landscape in the analogy is a function of different enzyme ratios. Each place you step is a different vector of enzyme ratios, and each altitude is a turnover rate, so you're looking for the spot where the altitude is lowest / the turnover rate is fastest. 

Now imagine that you find yourself in a ditch. The compass would lead you to the center of the ditch, at which you would be at the lowest point near you, so the compass would have nowhere lower to point. But what if there is an even lower ditch somewhere else? How do we find that lower point if the compass can't understand that even if this is the lowest point in the near vicinity, there might be a lower point somewhere else? To get around this, we use multiple explorers in this landscape. That way, if one of them gets stuck in a ditch, there are still others who can find a better solution. Each explorer can start in a different part of the landscape so their compasses will take them on different paths, finding different low points. We hope that one of the explorers will find the global lowest altitude on the landscape, although this is not guaranteed.

##

MCGD outputs a vector containing two types of information: the **optimized enzyme ratios**, and the **final concentration** of the compound of interest. The output vector is the list of optimized enzyme ratios, and the last value of the vector is the concentration of the compound of interest at then end of the model time.

An example of an output vector for a system with three enzymes could look like this: <3, 6, 1, -8.3>, where 3, 6, and 1 are the optimized enzyme ratios for the system, and -8.3 is negative one times the final concentration of the compound of interest.

The MCGD function takes a few **arguments**: NumberOfEnzymes, TotalEnzyme, NumberOfRuns, ThresholdGuess, GDPrecision, GDNumberOfSteps, and GDdtCutoff. MCGD also requires

The arguments for MCGD are as follows:

**NumberOfEnzymes** is the number of enzymes in the pathway being optimized. For example, a linear chain system of reactions with five substrates and a unique enzyme catalyzing each reaction from one substrate to the next would have four enzymes.

**TotalEnzyme** is the total concentration of enzyme the optimization algorithm has to work with. This constraint is important because if the algorithm had unlimited enzyme to work with, it could find a solution that is efficient but not practical due to an unreasonably high amount of enzyme. This concentration should take into account what concentrations of enzyme are feasible for the intended use of your pathway.

**NumberOfRuns** is the number of runs the algorithm will take. More runs can produce a better answer but will take longer.

**ThresholdGuess** is a vector that represents the initial guess for enzyme ratios. This list of values does not need to be very accurate; it serves only to keep the algorithm from wasting time computational power searching through awful enzyme ratio guesses. Using a simple 1:1 ratio as ThresholdGuess is perfectly fine. The vector you input for Threshold Guess should be the same length as the number of enzymes. For example, a four enzyme system could have an initial guess of c(1,1,1,1).

**GDPrecision** is short for Gradient Descent Precision and is the step size the algorithm takes. If the algorithm takes very small steps towards a solution, it will be able to find a more accurate answer, but it will also take longer, since more steps will be needed. Generally, 0.25 is an appropriate value for GDPrecision.

**GDNumberOfSteps** is the number of steps the algorithm will take each run it does. The more steps taken, the longer it will take the algorithm to do each run.

**GDCutoff** determines what level of accuracy is desired. If the algorithm starts adjusting values below this step of accuracy, it will terminate to avoid additional computation cost. If the total enzyme is 22.6 ug/ml, and an accuracy of .226 ug/ml is desired, then the GDCutoff value should be .01, or 1%.
